Repository KuriBus/server, pull requests merged in 2025-05, with the labels that each got.

#30 Redis를 이용한 좌표 저장 로직 구현
  build.gradle
  src/main/java/com/chatting/capstone/domain/location/controller/CoordinateController.java
  src/main/java/com/chatting/capstone/domain/location/entity/Portal.java
  src/main/java/com/chatting/capstone/domain/location/service/MovementService.java
  src/main/java/com/chatting/capstone/domain/location/service/UserLocationService.java
  src/main/java/com/chatting/capstone/domain/room/entity/Room.java
  src/main/java/com/chatting/capstone/domain/room/repository/RoomRepository.java
  src/main/java/com/chatting/capstone/domain/room/service/RoomService.java
  src/main/java/com/chatting/capstone/global/config/RedisConfig.java
  src/main/resources/application.yml
Labels: ✨ Feature

#32 feat/#31-chat-ai ai 연동 완료
  src/main/java/com/chatting/capstone/domain/chat/ai_ver/ClovaXClient.java
  src/main/java/com/chatting/capstone/domain/chat/ai_ver/ClovaXResponse.java
  src/main/java/com/chatting/capstone/domain/chat/controller/ChatController.java
  src/main/java/com/chatting/capstone/global/config/WebSocketConfig.java
  src/main/resources/application.yml
Labels: ✨ Feature

#36 fix/#35feat/#35-chat-subscribe test용 html수정
  src/main/resources/static/index.html
Labels: 🔨 Refactor, ✅ Test

#38 feat/#37-customization 에셋 저장, 전송 구현
  src/main/java/com/chatting/capstone/domain/customization/controller/CustomizationController.java
  src/main/java/com/chatting/capstone/domain/customization/dto/request/CustomizationRequest.java
  src/main/java/com/chatting/capstone/domain/customization/dto/response/CustomizationResponse.java
  src/main/java/com/chatting/capstone/domain/customization/entity/Customization.java
  src/main/java/com/chatting/capstone/domain/customization/repository/CustomizationRepository.java
  src/main/java/com/chatting/capstone/domain/customization/service/CustomizationService.java
  src/main/java/com/chatting/capstone/domain/user/entity/User.java
  src/main/resources/static/custom.html
Labels: ✨ Feature

#39 Redis 연동 설정 추가
  docker-compose-dev.yml
  src/main/resources/application.yml
Labels: 🗃 Database, 🐋 Docker, ✨ Feature

#40 브랜치 최신화를 위한 PR입니다.
  src/main/resources/application.yml
Labels: 📦 Chore, ✅ Test

#42 ddl-auto 변경 및 도메인 설정
  src/main/java/com/chatting/capstone/domain/user/entity/User.java
  src/main/resources/application.yml
Labels: 📦 Chore

#44 fix/#43-entity-tablename 엔티티별 table 이름 설정
  src/main/java/com/chatting/capstone/domain/chat/entity/Chat.java
  src/main/java/com/chatting/capstone/domain/customization/entity/Customization.java
  src/main/java/com/chatting/capstone/domain/location/entity/Portal.java
  src/main/java/com/chatting/capstone/domain/room/entity/Room.java
  src/main/java/com/chatting/capstone/domain/user/entity/User.java
Labels: 🔨 Refactor

#47 fix/#46-cors GlobalExceptionHandler 주석처리 및 cors 주소 추가
  src/main/java/com/chatting/capstone/global/config/SecurityConfig.java
  src/main/java/com/chatting/capstone/global/config/WebSocketConfig.java
  src/main/java/com/chatting/capstone/global/exception/GlobalExceptionHandler.java
Labels: 🔨 Refactor

#49 feat/#31-chat-ai userId request 삭제
  src/main/java/com/chatting/capstone/domain/chat/controller/ChatController.java
  src/main/java/com/chatting/capstone/domain/chat/dto/request/ChatRequest.java
  src/main/java/com/chatting/capstone/domain/chat/dto/response/ChatResponse.java
  src/main/java/com/chatting/capstone/domain/chat/service/ChatService.java
Labels: 🔨 Refactor

#51 fix/#50-chat-handshake-bug handshake 과정 삭제 및 경고 알림 추가
  src/main/java/com/chatting/capstone/domain/chat/controller/ChatController.java
  src/main/java/com/chatting/capstone/global/config/WebSocketConfig.java
Labels: 🐞 BugFix, ✨ Feature

#55 CD 워크플로우 .env 파일 접근 권한 오류 수정
  .github/workflows/cd.yml
Labels: 🐞 BugFix

#66 Dockerfile에서 jar 파일 경로 명시적으로 수정
  Dockerfile
Labels: 🐞 BugFix, 🐋 Docker

#59 fix/##58-chatting-view repo 및 service 수정
  src/main/java/com/chatting/capstone/domain/chat/repository/ChatRepository.java
  src/main/java/com/chatting/capstone/domain/chat/service/ChatService.java
Labels: 🐞 BugFix

#69 fix/#68-chat-prompt-subscribe-fix 프롬프트 및 구독 경로 수정
  src/main/java/com/chatting/capstone/domain/chat/ai_ver/ClovaXClient.java
  src/main/java/com/chatting/capstone/domain/chat/controller/ChatController.java
Labels: 🔨 Refactor

#71 fix/#67-asset-save bodyType 1개로 통일
  src/main/java/com/chatting/capstone/domain/customization/dto/request/CustomizationRequest.java
  src/main/java/com/chatting/capstone/domain/customization/dto/response/CustomizationResponse.java
  src/main/java/com/chatting/capstone/domain/customization/entity/Customization.java
  src/main/java/com/chatting/capstone/domain/customization/service/CustomizationService.java
  src/main/resources/static/custom.html
Labels: 🔨 Refactor

#74 fix/#27-chatting-delay 모더레이션 속도 개선
  src/main/java/com/chatting/capstone/domain/chat/ai_ver/ClovaXClient.java
  src/main/java/com/chatting/capstone/domain/chat/controller/ChatController.java
  src/main/java/com/chatting/capstone/global/moderation/ClovaService.java
  src/main/java/com/chatting/capstone/global/moderation/PerplexityService.java
Labels: 🐞 BugFix
