Repository KuriBus/server, pull requests merged in 2025-07, with the labels that each got.

#108 캐릭터가 화면 밖 좌표로 이동하는 현상 수정
  src/main/java/com/chatting/capstone/domain/location/controller/MovementController.java
Labels: 🐞 BugFix

#112 도메인 변경에 따른 Swagger 및 CORS 설정 수정
  src/main/java/com/chatting/capstone/global/config/SecurityConfig.java
  src/main/java/com/chatting/capstone/global/config/SwaggerConfig.java
  src/main/java/com/chatting/capstone/global/config/WebSocketConfig.java
  src/main/resources/static/front/BridgeScene.js
  src/main/resources/static/front/CharacterSelectScene.js
  src/main/resources/static/front/index.html
  src/main/resources/static/front/mainScene.js
Labels: 📦 Chore, 🔨 Refactor

#113 채팅 금지 시간 확인
  src/main/java/com/chatting/capstone/domain/chat/service/ChatService.java
Labels: ✨ Feature

#115 도메인 변경에 따른 CORS 정책 수정
  src/main/java/com/chatting/capstone/global/config/SecurityConfig.java
  src/main/java/com/chatting/capstone/global/config/WebSocketConfig.java
Labels: 🐞 BugFix, 📦 Chore

#119 swagger 자동화
  src/main/java/com/chatting/capstone/domain/chat/controller/ChatController.java
  src/main/java/com/chatting/capstone/domain/customization/controller/CustomizationController.java
  src/main/java/com/chatting/capstone/domain/customization/dto/request/CustomizationRequest.java
  src/main/java/com/chatting/capstone/domain/room/controller/RoomController.java
  src/main/java/com/chatting/capstone/domain/user/controller/UserController.java
  src/main/java/com/chatting/capstone/domain/user/dto/request/LoginRequest.java
  src/main/java/com/chatting/capstone/domain/user/dto/request/SignupRequest.java
  src/main/java/com/chatting/capstone/domain/user/dto/request/UserRequest.java
  src/main/java/com/chatting/capstone/global/common/HealthCheckController.java
Labels: 🌐 Infra

#123 Coordinate API 관련 Swagger 문서 개선
  src/main/java/com/chatting/capstone/domain/location/controller/CoordinateController.java
  src/main/java/com/chatting/capstone/domain/location/dto/request/CoordinateUpdateRequest.java
Labels: 🔨 Refactor
