Repository KuriBus/server, pull requests merged in 2025-06, with the labels that each got.

#81 fix/#80-movement 좌표 관련 수정
  src/main/java/com/chatting/capstone/domain/location/controller/MovementController.java
Labels: 📦 Chore

#85 불필요한 코드 정리
  src/main/java/com/chatting/capstone/domain/location/dto/request/InteractionRequest.java
  src/main/java/com/chatting/capstone/domain/room/dto/request/RoomRequest.java
  src/main/java/com/chatting/capstone/global/config/RoomInitializer.java
Labels: 🔨 Refactor

#87 feat/#86-customization-all 모든 유저 에셋 불러오기
  src/main/java/com/chatting/capstone/domain/customization/controller/CustomizationController.java
  src/main/java/com/chatting/capstone/domain/customization/service/CustomizationService.java
Labels: ✨ Feature

#88 좌표 수정
  src/main/java/com/chatting/capstone/domain/location/controller/MovementController.java
Labels: 🐞 BugFix

#89 프론트 파일 삽입
  src/main/resources/static/custom.html
  src/main/resources/static/front/BridgeScene.js
  src/main/resources/static/front/CharacterSelectScene.js
  src/main/resources/static/front/NicknameScene.js
  src/main/resources/static/front/StartScene.js
  src/main/resources/static/front/WorldMapScene.js
  src/main/resources/static/front/assets/audio/bridgebgm.mp3
  src/main/resources/static/front/assets/audio/classroombgm.mp3
  src/main/resources/static/front/assets/audio/culturelandbgm.mp3
  src/main/resources/static/front/assets/audio/parkbgm.mp3
  src/main/resources/static/front/assets/boy1.png
  src/main/resources/static/front/assets/boy2.png
  src/main/resources/static/front/assets/boy3.png
  src/main/resources/static/front/assets/bridge1.png
  src/main/resources/static/front/assets/bridge2.png
  src/main/resources/static/front/assets/bridge3.png
  src/main/resources/static/front/assets/chatbox.png
  src/main/resources/static/front/assets/classroom.png
  src/main/resources/static/front/assets/cultureland.png
  src/main/resources/static/front/assets/girl1.png
  src/main/resources/static/front/assets/girl2.png
  src/main/resources/static/front/assets/girl3.png
  src/main/resources/static/front/assets/invisable.png
  src/main/resources/static/front/assets/logo.png
  src/main/resources/static/front/assets/main.jpg
  src/main/resources/static/front/assets/nicknamebg.png
  src/main/resources/static/front/assets/park.png
  src/main/resources/static/front/assets/start_button.png
  src/main/resources/static/front/assets/worldbg.png
  src/main/resources/static/front/game.js
  src/main/resources/static/front/index.html
  src/main/resources/static/front/mainScene.js
  src/main/resources/static/index.html
Labels: 🌏 Deploy

#90 배포..
  src/main/resources/static/front/mainScene.js
Labels: 🌏 Deploy

#92 배포..
  src/main/resources/static/front/BridgeScene.js
  src/main/resources/static/front/mainScene.js
Labels: 🌏 Deploy

#103 스웨거 관련 시큐리티 경로 추가
  src/main/java/com/chatting/capstone/global/config/SecurityConfig.java
Labels: 🌐 Infra

#104 스웨거 security
  src/main/java/com/chatting/capstone/global/config/SwaggerConfig.java
Labels: 🌐 Infra
