Repository KuriBus/server, pull requests merged in 2025-04, with the labels that each got.

#22 방 구현
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  build.gradle
  src/main/java/com/chatting/capstone/domain/room/controller/RoomController.java
  src/main/java/com/chatting/capstone/domain/room/dto/response/RoomResponse.java
  src/main/java/com/chatting/capstone/domain/room/entity/Room.java
  src/main/java/com/chatting/capstone/domain/room/repository/RoomRepository.java
  src/main/java/com/chatting/capstone/domain/room/service/RoomService.java
  src/main/java/com/chatting/capstone/domain/user/dto/request/UserRequest.java
  src/main/java/com/chatting/capstone/domain/user/dto/response/UserResponse.java
  src/main/java/com/chatting/capstone/domain/user/service/UserService.java
  src/main/java/com/chatting/capstone/global/config/RoomInitializer.java
  src/main/java/com/chatting/capstone/global/exception/GlobalExceptionHandler.java
  src/main/java/com/chatting/capstone/global/exception/ResponseStatus.java
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: ✨ Feature, 🔨 Refactor

#23 RDS 환경에서 room_id가 NULL로 삽입되는 문제 해결
  src/main/java/com/chatting/capstone/domain/user/entity/User.java
  src/main/java/com/chatting/capstone/global/config/RoomInitializer.java
Labels: 🐞 BugFix

#16 feat #7 채팅 구현 및 환경 설정
  src/main/java/com/chatting/capstone/CapstoneApplication.java
  src/main/java/com/chatting/capstone/domain/chat/controller/ChatController.java
  src/main/java/com/chatting/capstone/domain/chat/dto/request/ChatRequest.java
  src/main/java/com/chatting/capstone/domain/chat/dto/response/ChatResponse.java
  src/main/java/com/chatting/capstone/domain/chat/entity/Chat.java
  src/main/java/com/chatting/capstone/domain/chat/repository/ChatRepository.java
  src/main/java/com/chatting/capstone/domain/chat/service/ChatService.java
  src/main/java/com/chatting/capstone/global/config/WebSocketConfig.java
  src/main/java/com/chatting/capstone/global/moderation/PerplexityService.java
  src/main/java/com/chatting/capstone/global/test.java
  src/main/resources/application.yml
Labels: ✨ Feature

#26 방 로직 개선
  src/main/java/com/chatting/capstone/domain/room/controller/RoomController.java
  src/main/java/com/chatting/capstone/domain/room/dto/request/RoomRequest.java
  src/main/java/com/chatting/capstone/domain/room/service/RoomService.java
  src/main/java/com/chatting/capstone/domain/user/controller/UserController.java
  src/main/java/com/chatting/capstone/domain/user/entity/User.java
  src/main/java/com/chatting/capstone/domain/user/service/UserService.java
  src/main/java/com/chatting/capstone/global/config/RoomInitializer.java
  src/main/resources/application.yml
Labels: 🐞 BugFix, 📦 Chore, ✨ Feature, 🔨 Refactor
